apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent_volumes.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: stump-config
    namespace: stump
    envs:
      - config.env
