---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stump-data-pvc
  namespace: stump
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
